.libPaths(c("E:/R/R_libs", .libPaths()))
library(Seurat)
nCoV.integrated <- readRDS("E:/Claude code/shengxin/covid_balf/nCoV.rds")
macrophage_clusters <- c('0','1','2','3','4','5','7','8','10','11','12','18','21','22','23','26')
Macrophage <- subset(nCoV.integrated, idents = macrophage_clusters)
cat("=== sample column ===\n")
print(sort(unique(Macrophage@meta.data$sample)))
cat("\n=== sample_new column ===\n")
print(sort(unique(Macrophage@meta.data$sample_new)))
